REQUEST:
  ACTIVE: \x81
  DISABLE_USER_ENTRY: \x94
  ENABLE_USER_ENTRY: \x93
  GET_COMMAND_VERSION: \x84
  GET_CURRENT_CHANNEL: \x87
  GET_CURRENT_CHANNEL_MT: \8B
  GET_CURRENT_TIME: \x91
  GET_PRIMARY_STATUS: \x83
  GET_PRIMARY_STATUS_MT: \x8A
  GET_RETURN_VALUE: \x95
  GET_SIGNAL_QUALITY: \x90
  GET_SIGNAL_QUALITY_MT: \x9D
  GET_TUNER: \x9A
  GET_USER_COMMAND: \x92
  OPEN_USER_CHANNEL: \xA6
  OPEN_USER_CHANNEL_MT: \x9F
  PREFIX: \xFA
  REBOOT: \x96
  SEND_USER_COMMAND: \xA5
  STANDBY: \x81
RESPONSE:
  ACK_CMD: \xF0
  ACK_FCNOK: \xF4
  ACK_PARAMS: \xF2
  ACK_RESET: \xF6
  CMDBUF_OVFL: \xFF
  DATA_ERROR: \xFD
  NACK_BUSY: \xF7
  NACK_CMD: \xF1
  NACK_FCNOK: \xF5
  NACK_INUSE: \xF9
  NACK_PARAMS: \xF3
  NACK_PREFIX: \xFB
